# Generated by Django 4.0.1 on 2022-02-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='itn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
