# Generated by Django 4.0.1 on 2022-02-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
