# Generated by Django 4.0.1 on 2022-01-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ads_created_at_ads_tags_ads_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
