# Generated by Django 4.0.1 on 2022-02-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seller_itn'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
