# Generated by Django 4.0.1 on 2022-01-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_basemodel_rename_title_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=' ', max_length=255, null=True, unique=True),
        ),
    ]
